/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStudiesRouteImport } from './routes/_authenticated/studies'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAutomationsWorkflowsRouteImport } from './routes/_authenticated/automations.workflows'
import { Route as AuthenticatedAutomationsWebhooksRouteImport } from './routes/_authenticated/automations.webhooks'
import { Route as AuthenticatedAutomationsSettingsRouteImport } from './routes/_authenticated/automations.settings'
import { Route as AuthenticatedAutomationsIntegrationsRouteImport } from './routes/_authenticated/automations.integrations'
import { Route as AuthenticatedAutomationsExecutionsRouteImport } from './routes/_authenticated/automations.executions'
import { Route as AuthenticatedAutomationsEventsRouteImport } from './routes/_authenticated/automations.events'
import { Route as ApiPublicWebhooksN8nRouteImport } from './routes/api/public/webhooks/n8n'
import { Route as ApiPublicHooksCheckRemindersRouteImport } from './routes/api/public/hooks/check-reminders'
import { Route as AuthenticatedAutomationsIntegrationsN8nRouteImport } from './routes/_authenticated/automations.integrations.n8n'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudiesRoute = AuthenticatedStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsWorkflowsRoute =
  AuthenticatedAutomationsWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsWebhooksRoute =
  AuthenticatedAutomationsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsSettingsRoute =
  AuthenticatedAutomationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsIntegrationsRoute =
  AuthenticatedAutomationsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsExecutionsRoute =
  AuthenticatedAutomationsExecutionsRouteImport.update({
    id: '/executions',
    path: '/executions',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsEventsRoute =
  AuthenticatedAutomationsEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const ApiPublicWebhooksN8nRoute = ApiPublicWebhooksN8nRouteImport.update({
  id: '/api/public/webhooks/n8n',
  path: '/api/public/webhooks/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckRemindersRoute =
  ApiPublicHooksCheckRemindersRouteImport.update({
    id: '/api/public/hooks/check-reminders',
    path: '/api/public/hooks/check-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAutomationsIntegrationsN8nRoute =
  AuthenticatedAutomationsIntegrationsN8nRouteImport.update({
    id: '/n8n',
    path: '/n8n',
    getParentRoute: () => AuthenticatedAutomationsIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studies': typeof AuthenticatedStudiesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/automations/events': typeof AuthenticatedAutomationsEventsRoute
  '/automations/executions': typeof AuthenticatedAutomationsExecutionsRoute
  '/automations/integrations': typeof AuthenticatedAutomationsIntegrationsRouteWithChildren
  '/automations/settings': typeof AuthenticatedAutomationsSettingsRoute
  '/automations/webhooks': typeof AuthenticatedAutomationsWebhooksRoute
  '/automations/workflows': typeof AuthenticatedAutomationsWorkflowsRoute
  '/automations/integrations/n8n': typeof AuthenticatedAutomationsIntegrationsN8nRoute
  '/api/public/hooks/check-reminders': typeof ApiPublicHooksCheckRemindersRoute
  '/api/public/webhooks/n8n': typeof ApiPublicWebhooksN8nRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studies': typeof AuthenticatedStudiesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/automations/events': typeof AuthenticatedAutomationsEventsRoute
  '/automations/executions': typeof AuthenticatedAutomationsExecutionsRoute
  '/automations/integrations': typeof AuthenticatedAutomationsIntegrationsRouteWithChildren
  '/automations/settings': typeof AuthenticatedAutomationsSettingsRoute
  '/automations/webhooks': typeof AuthenticatedAutomationsWebhooksRoute
  '/automations/workflows': typeof AuthenticatedAutomationsWorkflowsRoute
  '/automations/integrations/n8n': typeof AuthenticatedAutomationsIntegrationsN8nRoute
  '/api/public/hooks/check-reminders': typeof ApiPublicHooksCheckRemindersRoute
  '/api/public/webhooks/n8n': typeof ApiPublicWebhooksN8nRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studies': typeof AuthenticatedStudiesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/automations/events': typeof AuthenticatedAutomationsEventsRoute
  '/_authenticated/automations/executions': typeof AuthenticatedAutomationsExecutionsRoute
  '/_authenticated/automations/integrations': typeof AuthenticatedAutomationsIntegrationsRouteWithChildren
  '/_authenticated/automations/settings': typeof AuthenticatedAutomationsSettingsRoute
  '/_authenticated/automations/webhooks': typeof AuthenticatedAutomationsWebhooksRoute
  '/_authenticated/automations/workflows': typeof AuthenticatedAutomationsWorkflowsRoute
  '/_authenticated/automations/integrations/n8n': typeof AuthenticatedAutomationsIntegrationsN8nRoute
  '/api/public/hooks/check-reminders': typeof ApiPublicHooksCheckRemindersRoute
  '/api/public/webhooks/n8n': typeof ApiPublicWebhooksN8nRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/activity'
    | '/automations'
    | '/calendar'
    | '/finance'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/reminders'
    | '/settings'
    | '/studies'
    | '/tasks'
    | '/automations/events'
    | '/automations/executions'
    | '/automations/integrations'
    | '/automations/settings'
    | '/automations/webhooks'
    | '/automations/workflows'
    | '/automations/integrations/n8n'
    | '/api/public/hooks/check-reminders'
    | '/api/public/webhooks/n8n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/activity'
    | '/automations'
    | '/calendar'
    | '/finance'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/reminders'
    | '/settings'
    | '/studies'
    | '/tasks'
    | '/'
    | '/automations/events'
    | '/automations/executions'
    | '/automations/integrations'
    | '/automations/settings'
    | '/automations/webhooks'
    | '/automations/workflows'
    | '/automations/integrations/n8n'
    | '/api/public/hooks/check-reminders'
    | '/api/public/webhooks/n8n'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/activity'
    | '/_authenticated/automations'
    | '/_authenticated/calendar'
    | '/_authenticated/finance'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/notes'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/reminders'
    | '/_authenticated/settings'
    | '/_authenticated/studies'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/automations/events'
    | '/_authenticated/automations/executions'
    | '/_authenticated/automations/integrations'
    | '/_authenticated/automations/settings'
    | '/_authenticated/automations/webhooks'
    | '/_authenticated/automations/workflows'
    | '/_authenticated/automations/integrations/n8n'
    | '/api/public/hooks/check-reminders'
    | '/api/public/webhooks/n8n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksCheckRemindersRoute: typeof ApiPublicHooksCheckRemindersRoute
  ApiPublicWebhooksN8nRoute: typeof ApiPublicWebhooksN8nRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studies': {
      id: '/_authenticated/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof AuthenticatedStudiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations/workflows': {
      id: '/_authenticated/automations/workflows'
      path: '/workflows'
      fullPath: '/automations/workflows'
      preLoaderRoute: typeof AuthenticatedAutomationsWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/webhooks': {
      id: '/_authenticated/automations/webhooks'
      path: '/webhooks'
      fullPath: '/automations/webhooks'
      preLoaderRoute: typeof AuthenticatedAutomationsWebhooksRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/settings': {
      id: '/_authenticated/automations/settings'
      path: '/settings'
      fullPath: '/automations/settings'
      preLoaderRoute: typeof AuthenticatedAutomationsSettingsRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/integrations': {
      id: '/_authenticated/automations/integrations'
      path: '/integrations'
      fullPath: '/automations/integrations'
      preLoaderRoute: typeof AuthenticatedAutomationsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/executions': {
      id: '/_authenticated/automations/executions'
      path: '/executions'
      fullPath: '/automations/executions'
      preLoaderRoute: typeof AuthenticatedAutomationsExecutionsRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/events': {
      id: '/_authenticated/automations/events'
      path: '/events'
      fullPath: '/automations/events'
      preLoaderRoute: typeof AuthenticatedAutomationsEventsRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/api/public/webhooks/n8n': {
      id: '/api/public/webhooks/n8n'
      path: '/api/public/webhooks/n8n'
      fullPath: '/api/public/webhooks/n8n'
      preLoaderRoute: typeof ApiPublicWebhooksN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-reminders': {
      id: '/api/public/hooks/check-reminders'
      path: '/api/public/hooks/check-reminders'
      fullPath: '/api/public/hooks/check-reminders'
      preLoaderRoute: typeof ApiPublicHooksCheckRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automations/integrations/n8n': {
      id: '/_authenticated/automations/integrations/n8n'
      path: '/n8n'
      fullPath: '/automations/integrations/n8n'
      preLoaderRoute: typeof AuthenticatedAutomationsIntegrationsN8nRouteImport
      parentRoute: typeof AuthenticatedAutomationsIntegrationsRoute
    }
  }
}

interface AuthenticatedAutomationsIntegrationsRouteChildren {
  AuthenticatedAutomationsIntegrationsN8nRoute: typeof AuthenticatedAutomationsIntegrationsN8nRoute
}

const AuthenticatedAutomationsIntegrationsRouteChildren: AuthenticatedAutomationsIntegrationsRouteChildren =
  {
    AuthenticatedAutomationsIntegrationsN8nRoute:
      AuthenticatedAutomationsIntegrationsN8nRoute,
  }

const AuthenticatedAutomationsIntegrationsRouteWithChildren =
  AuthenticatedAutomationsIntegrationsRoute._addFileChildren(
    AuthenticatedAutomationsIntegrationsRouteChildren,
  )

interface AuthenticatedAutomationsRouteChildren {
  AuthenticatedAutomationsEventsRoute: typeof AuthenticatedAutomationsEventsRoute
  AuthenticatedAutomationsExecutionsRoute: typeof AuthenticatedAutomationsExecutionsRoute
  AuthenticatedAutomationsIntegrationsRoute: typeof AuthenticatedAutomationsIntegrationsRouteWithChildren
  AuthenticatedAutomationsSettingsRoute: typeof AuthenticatedAutomationsSettingsRoute
  AuthenticatedAutomationsWebhooksRoute: typeof AuthenticatedAutomationsWebhooksRoute
  AuthenticatedAutomationsWorkflowsRoute: typeof AuthenticatedAutomationsWorkflowsRoute
}

const AuthenticatedAutomationsRouteChildren: AuthenticatedAutomationsRouteChildren =
  {
    AuthenticatedAutomationsEventsRoute: AuthenticatedAutomationsEventsRoute,
    AuthenticatedAutomationsExecutionsRoute:
      AuthenticatedAutomationsExecutionsRoute,
    AuthenticatedAutomationsIntegrationsRoute:
      AuthenticatedAutomationsIntegrationsRouteWithChildren,
    AuthenticatedAutomationsSettingsRoute:
      AuthenticatedAutomationsSettingsRoute,
    AuthenticatedAutomationsWebhooksRoute:
      AuthenticatedAutomationsWebhooksRoute,
    AuthenticatedAutomationsWorkflowsRoute:
      AuthenticatedAutomationsWorkflowsRoute,
  }

const AuthenticatedAutomationsRouteWithChildren =
  AuthenticatedAutomationsRoute._addFileChildren(
    AuthenticatedAutomationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudiesRoute: typeof AuthenticatedStudiesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudiesRoute: AuthenticatedStudiesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksCheckRemindersRoute: ApiPublicHooksCheckRemindersRoute,
  ApiPublicWebhooksN8nRoute: ApiPublicWebhooksN8nRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
